### ISSUE TITLE
set_params should not modify objects in place

### ISSUE THREAD

**Issue by JasonGross** [JasonGross/guarantees-based-mechanistic-interpretability#17]
I spent the past ~30 minutes confused about why my code was breaking, and it boiled down to "`set_params` mutates the object when I was expecting it not to".  I think this is likely to bite us again in the future.

**Comment by euanong** [comment]
fixed (with test cases) -- the deep setattr is annotated with None type (to make it clear it mutates state), and set_params is non-mutating
